import { buildGoogleFontsUrl } from './fontPairings';

export function buildCssExport(colors, pairing) {
  const colorLines = colors
    .map((hex, index) => `  --color-${index + 1}: ${hex};`)
    .join('\n');
  const fontsUrl = buildGoogleFontsUrl([pairing.display, pairing.body]);

  return `/* Generated by Prism */
@import url('${fontsUrl}');

:root {
${colorLines}
  --font-display: '${pairing.display.name}', serif;
  --font-body: '${pairing.body.name}', sans-serif;
}
`;
}
